spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.jwkSetUri}
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: ${dataSourceUrl}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${dataSourceUserName}
    password: ${dataSourcePassword}
springdoc:
  enable-spring-security: true

